apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: remediation-api
  labels:
    app.kubernetes.io/part-of: remediation-stack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: remediation-api
subjects:
  - kind: ServiceAccount
    name: remediation-api
    namespace: remediation-app
