apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: agent-console
  namespace: remediation-app
  labels:
    app.kubernetes.io/name: agent-console
    app.kubernetes.io/part-of: remediation-stack
spec: {}
