apiVersion: v1
kind: Service
metadata:
  name: remediation-api
  namespace: remediation-app
  labels:
    app.kubernetes.io/name: remediation-api
    app.kubernetes.io/part-of: remediation-stack
spec:
  selector:
    app.kubernetes.io/name: remediation-api
  ports:
    - name: http
      port: 8787
      targetPort: 8787
      protocol: TCP
  type: ClusterIP
